version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n_workflow_automation
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin # Cambia este usuario
      - N8N_BASIC_AUTH_PASSWORD=password # Cambia esta contraseña
      - TZ=America/Bogota # Ajusta a tu zona horaria
      - GENERIC_TIMEZONE=America/Bogota
    volumes:
      - ./n8n_data:/home/node/.n8n
    command: /bin/sh -c "n8n start"

  evolution-api:
    image: atendai/evolution-api
    container_name: evolution_api_service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - API_KEY=tu_api_key_secreta # ¡IMPORTANTE! Cambia esta clave
      - SERVER_URL=http://localhost:8080
      # Configuración de la base de datos (opcional, usa archivos por defecto)
      - DATABASE_ENABLED=false
      # Otras variables de entorno de Evolution API que necesites
    volumes:
      - ./evolution_api_data:/app/dist/instances

volumes:
  n8n_data:
  evolution_api_data: